### ISSUE TITLE
Contao3-Version nicht über Composer installierbar

### ISSUE THREAD

**Issue by tognit** [MetaModels/attribute_geoprotection#3]
Wenn ich das attribute über den Composer installieren möchte erhalte ich nachfolgende Meldung

```
Problem 1 - Installation request for metamodels/attribute_geoprotection dev-contao3 -> satisfiable by metamodels/attribute_geoprotection[dev-contao3]. - metamodels/attribute_geoprotection dev-contao3 requires contao/core ~2.11 -> no matching package found.
```

So wie ich das in der "contao3/composer.json" sehe, ist diese nur bis Contao 2.11 kompatibel.

**Comment by xantippe** [comment]
geht
![shot144](https://cloud.githubusercontent.com/assets/1045318/13493454/82c66108-e13e-11e5-9c7c-1dfeaccc0e86.jpg)
