### ISSUE TITLE
Fatal error: Class 'MetaModels\Attribute\Geoprotection\Helper' not found 

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/attribute_geoprotection#9]
Contao 3.4.5:

Folgende Fehlermeldung erscheint, wenn man versucht, im Datensatz unter Metamodels, den Attribut-Typ Geoprotection auszuwählen. Es erfolgt sofort ein:

```

Fatal error: Class 'MetaModels\Attribute\Geoprotection\Helper' not found in /composer/vendor/metamodels/attribute_geoprotection/src/MetaModels/DcGeneral/Events/Table/Attribute/GeoProtection/Subscriber.php on line 68

```

**Comment by discordier** [comment]
Wie installiert? 
Via composer?
Autoload informationen aktuell?
Anscheinend wurde bei dir die Klasse nicht im autoloader registriert.

**Comment by kein-nickname** [comment]
@discordier: Ganz normal per Composer.

**Comment by kein-nickname** [comment]
@discordier Hab gerade Geoprotection deinstalliert und neuinstalliert. Gleiches Problem.
Beim Versuch eines erneuten Sync über Composer erhielt ich

````
Fatal error: Cannot redeclare class runonceJob in /system/modules/geolocation/config/runonce.php on line 42
````

**Comment by discordier** [comment]
Da scheint wohl dann was in den basis libraries geolocation und geoprotection was schief zu laufen.
@stefanheimes ist dir da was bekannt?

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@kein-nickname could you please have a final look at this and tell if your issue has been resolved?
